name: benosafrimed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.0.0
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.11
  flutter_google_places: ^0.3.0
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  file_picker: ^8.1.7
  intl: ^0.20.2
  geocoding: ^3.0.0
  http: ^0.13.6
  universal_html: ^2.2.4
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add your image asset here, ensuring correct path & filename
  assets:
    - assets/images/afrimed_logo.png
